/**
 * Audio Service
 *
 * Design decision: audio files served from /audio/{lesson_id}/{sentence_id}.opus
 * Files are pre-generated by the backend pipeline using Google WaveNet TTS.
 * No streaming — files are small (<50KB each), prefetch on lesson load.
 * Fallback: if file 404s, hide audio button silently (no error shown to user).
 */

class AudioService {
  private cache: Map<string, HTMLAudioElement> = new Map();

  private key(lessonId: string, sentenceId: string): string {
    return `${lessonId}/${sentenceId}`;
  }

  private url(lessonId: string, sentenceId: string): string {
    return `/audio/${lessonId}/${sentenceId}.opus`;
  }

  async play(lessonId: string, sentenceId: string): Promise<void> {
    const k = this.key(lessonId, sentenceId);
    let audio = this.cache.get(k);

    if (!audio) {
      audio = new Audio(this.url(lessonId, sentenceId));
      this.cache.set(k, audio);
    }

    try {
      audio.currentTime = 0;
      await audio.play();
    } catch {
      // 404 or browser policy — fail silently
    }
  }

  prefetch(lessonId: string, sentenceIds: string[]): void {
    for (const id of sentenceIds) {
      const k = this.key(lessonId, id);
      if (!this.cache.has(k)) {
        const audio = new Audio(this.url(lessonId, id));
        audio.preload = 'auto';
        this.cache.set(k, audio);
      }
    }
  }
}

export const audioService = new AudioService();
